version = 0
commit_goodlist = []

[authorization."Kan-Ru Chen <kanru@kanru.info>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 374F F2AD 0A12 935F D0B0  C84F 1B13 2E01 CEC6 AD46
Comment: Kan-Ru Chen (陳侃如) <ckanru@gmail.com>
Comment: Kan-Ru Chen (陳侃如) <kanru@kanru.info>
Comment: Kan-Ru Chen (陳侃如) <koster@debian.org>

xsFNBErbyYoBEADPKUSVdYiKrWCEl2xk99gcEZghczDpm2/z0+UKwSFlwWO39A4i
JsDYhtDJPuFi/6dlr544gurTLF9S/8tmilYpEXukls1KcAwmj520TbeCTf/4w0tR
/i8m3GIasg9gRowNq9FnM6RaE4BCBGbhH9hQP3tKPsmS0rRTot6t1UkKGmzSW0BU
zc1VDKMDXdrJFX67rjfOGRjTQFBv8bEM93Cw/OUaNOuCMtJSklxpLrtGxS5cLpX/
7sfBV+aHOLIy2lBPYtZ8T5wrlRZHxlqumCacLdItvp3CCMNq1CGbMBE9mnoPOQKe
gZE5jq2km0bEWxoqrAup2Gqv1cwK1wSM4Zp/xN7MRUND5RH6ZCJ68Eqrh6b+WpT9
fEVATLl3T9pdYWPN1P2bZDh5Ma4LE0X3mQKUzivnvW91BAo73IVZN+Q/nmuWlCQA
FZrJffPjWscXVwEiMViMJBN72sgMWXii8NUT1G9/rOSt+Pt8J3IyLwv9hK9J/r14
fRwnOZtTUT/oaGYl1SmIMbCFLWYWLBkJFpkgsZZJpMW9bb6PVHWSOveWWhTUOWQS
8XavJl9McLZdDh7+DV7ZZx+rSIcDtjLmH7tjWCZh671D0S0Aw7mSpmFnPRkJLMFA
TTp54QceYljUInquegGRWEgMwz6GqeHnY6dEMVw+eH3yRF/CzPBHN1WliwARAQAB
zSpLYW4tUnUgQ2hlbiAo6Zmz5L6D5aaCKSA8Y2thbnJ1QGdtYWlsLmNvbT7CwY4E
EwEIACEFAksDsKkCGwMFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AAIQkQGxMuAc7G
rUYWIQQ3T/KtChKTX9CwyE8bEy4BzsatRoTuD/9WNcOdRMmkXk28Tiv24PgPGElg
Ax4yxhEY7K/G1wSQU/zF1JILkk2xH0QoeaWnkqg3xbumASrThk83WbZY4h6wRKem
t2pv0vyjF3jQBGq7OOvXaHVUkFfz29rliFLVsPwFmXtByYbWHuiG3tsLoMmF+0FY
EGSXGR2/BbxVJdQ1UgVszz44pylNsBRdDvqxnL91g02fjjdRsAhEYvvKdlwJRQkQ
s19pZeYL9vpk1DtOK3Vp0LyvMDhAztY4HYxFoAZtj/feq8zUGQNGA1aN37fbEDb4
VcbIELcezWbimuvShl/jy+sYTtfG1md7/IbQ2TBTUVW/KkI4fTU+r+VTq2SR602W
UKhaih6FCLVC9YCN2xIKEaVKwuGWfeGrCkQSnb5b03xsOINpPmvFzcFAAZ2FjUNp
ZGGSpec8b9DcBPj7tT/v+2VG9qyKyPWAfnorXuttaplnVMSD1hmVfpllyPAuvkeP
akiEKexD+YLHASZ91ScQy8fc2ryE8wjWfcXJesgoa2c9vHP9zr72yU7xth0iJI4V
NdrGyVbQXWRfXc6Byw/2WMbzME6546iF7JVOqgzsqSDhioKQ45y8OWs/qcAn6jm/
jXbHz2ZlKkoZKCGNc93Fe9P/oeVzTPieb+HRcC9OIpDXef6KG93KywzWzFvuEOAW
7vO5LFCXOJx2Vyaibs0pS2FuLVJ1IENoZW4gKOmZs+S+g+WmgikgPGthbnJ1QDB4
bGFiLm9yZz7CwY4EMAEIADgWIQQ3T/KtChKTX9CwyE8bEy4BzsatRgUCXHE0SRod
IDB4bGFiLm9yZyBpcyBub3cgZGVmdW5jdAAKCRAbEy4BzsatRmFZD/93sdRGuUNG
n0X6dJJpjzEQ8I9Ds5vnQM5nZHWngRSU5n5TfVNyLI1XPpqSe1h7J/UDUlpPRQiL
/7Qad+V0adNc4rRJdaHVdUh7Ysz/ywW1Ihn44QPpf2A+tDUeJgGM8GNJWdAcGp1g
4wX+k5dPdNCOPib+fXZ5ZIP4wQY2a8kKf6Ew1Y6fuIfMpnQ24jBEVLDUVRdP7RF7
AMB/pAm4htT7+eB687MUYxXExJJ9q39TlDWi3O9Rx4yfJ1qNVBOXPVTGwF6t2s1V
X4kx0o1nKBz7O04x53JFofuaG+TvA5dZR+Y7K6ZSYOMxcMq4RLvGmYZE9hBeyD4g
0tWdkGqIQ36bjqnQbH3Pp/GUedI4/KHsCCWUG46CPi0QGjAURIxEaJXlzoGAVloq
wXVJpZpL4uLYXXG7n1Z3Q0REv2ZwDekFiuoNauyy+7L6jMIAWzj6qjTvcjk55ms3
65FbLtw4xgVi1rbABmJVy7ODy1C4Lcp9jr0Pjezl+wen7z7d+AoHLEbNOVcV/5bs
TCC3++ljFJJ4AlyCdQ9q/xajQVwtuZTdIKMFtTA5TDOL42heogUOukCb+b3zXcx8
4FZ+hkrL/G+/kYloROoRlxQwbyid6+ToC16z3NsBzvIa13hzK70xKm5gIZWSdl3R
AaPkuK19CZJBH0Tp3fkiwX7Ja8Ne922R/8LBjgQTAQgAIQUCTGZ9jAIbAwULCQgH
AwUVCgkICwUWAgMBAAIeAQIXgAAhCRAbEy4BzsatRhYhBDdP8q0KEpNf0LDITxsT
LgHOxq1GfH4P/iWE2H1GrNwYDOhrEX8dX0Q6xJpDAHW7RU8oQOwGWpBrcaHYhoMH
Kp24aYdNrMxqlqDLmLdtlInS/j1WnjWiKSuNFqOgAL/6ADcCMLR/4bs9WaGgpO2B
6aZ8nteCOHfX5GQRJ2/93zhO40Qeauqdz6pf5W2/Vpia4Xwp4RdDR3fkfbLcHICX
7NP0xtevADliQmHT/yfkQfoJdUYd5XYidtuFl1dtA05EDxpxOBtIkAM8oa2YiuI0
Zxqooob3gJm0dUSEe/egqbUCRA6T1BDR5BhrkCg+wZsCxdkB68aze7HvKCdErUdF
sH7xLsElWepB3+ASwh2jKDrqu9i4fnm1+i4o2rka+X6GSXV8NYU0T1TFK1ayEUUb
FzcqZ9VLOygWbzF35pDkPAKt7thtQsPENUEN3k/D0hTBuoVHl708TcQCiZFDd+yb
ZFDD50BOb9RDT5l/wfIeACsgHoixO+YLO8gaIua8fnH1U5IqNC2o2OWkUOobnvca
/Hm4Awf9/x02/g29FkXnfJxac5jmki1qXSgDrsO34O5sIXgqoTmOc7FAWZBwklO4
LqXJbax4CKTifB3ssisJHMMFnW1bEH05xLYhwwCL4zZw3DAPuQSZidWbQOQxcaBa
slpmDK93IU1/DuSniA8W19V5UIhPJQu4zmFQOc8GF8frwA/KWp1IAsJKzSpLYW4t
UnUgQ2hlbiAo6Zmz5L6D5aaCKSA8a2FucnVAa2FucnUuaW5mbz7CwY4EEwEIACEC
GwMFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AFAkxomHMAIQkQGxMuAc7GrUYWIQQ3
T/KtChKTX9CwyE8bEy4BzsatRhmvEACG6zv/V2vXrmABiD2rV/JGC4/fW1AXKpvK
mhbOylDW3epC3a6AV3GZE7UYYuvnbqWlKoKB8AmIsXAa63kZhYNB6dmQxG6oNQxf
OXbK9PV5R2DUWbQ6UM1t3AM8lScDHaXMIAqDkrjSxAI+QCGVtfCTwxwezS6CUSj1
msyz9bmdYaQi1TVwxoPYOEDOq5ZmrRZLEGbBAHdiOl9SJD+AXeR3NSg875PWCiFe
7r6zg7kUuUaHSjMiwVDOJDp4nj3eYCkEUSVA46vQwsgRewziguvFzqrfE6pKkszq
U+kaIrWdzDkMxlmMDNuuChC+grhaMFqT/MHY0zgAd7WCPTDV3gG2xbxaTzpbmzgI
PSdwbpSceFXMWte439L5P8PFjEulQpbFlxZLYqZdMxcpS0q6WOkKSe4zFflaZbWY
aeY5wHE9W8c29h4L/oue42VxbFF9zZPxbp8tAaXHd+81SbT9yLtb9qSWF3JQd+s3
lSYojrXpc3e0XvCmtIWsLER8w1WD5+oCkI8fS794DdPtlF/r+JcrAzcYrFx4eXm6
KfUVbpRb4esVO9qR28oYuT59MFxF0z6hrf1Eu/MdZYLda8gkrNozPDNh+MhbwXbB
/ilphD90ZAn1rR0dxxJOuLO6uqDAtpubk4t3E8k8pY4gzD/ShaGYPEwriw3xPFJ5
7qmfdmOB3cLBjgQTAQgAIQIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAUCStvM
GwAhCRAbEy4BzsatRhYhBDdP8q0KEpNf0LDITxsTLgHOxq1Gv1kP/i5JGyxdshpI
BDMq210Nqzy0vbck6rqmq9RnJnaPXTz2wttJebNFsx70cFAqpJOx5l5THMhGsLmK
7QVbiWE8l0q4uspygi7bG9getYlzPe/ncScgjUzq4cT7PyjJdEBtUDWaYywK6S9M
sXnyuEjO+m6xeSq04bqq5gUnjWZpZDb34dxM8/SdxkZsLiq/eOHrwdfjYlYk6FML
lEl82H0loHl+mWj1I+XCxWcwpMHYVdIj0C1tK+WzKcg083Q/WFw7DH6TefFrjQ2n
v1bm1gLShpQo3TWowq5t5GuGWx0Bqn1MESH59Pky09V5em6VafMjqP8+25gvvN4b
u1m7+ONv/A04w5+7YBvrE4MmXDtuKFHlqrlfAA9+2QBMj38HGg6Tob3nHGDTSlxR
GnZOgiFS0KAmBC/M65p+et4fqnnuDn1vdoFP/PR0B435sPHh0VSL6MXINpqahNt6
bE5/6CzD7dwwf9WM53hi7HVLwP6Zc72rPhVijjxRgUKyS3Qc5w3VqmHgX5UWb/87
dZ+1P6Fl3p7gMp+UnEF8JmXHSLEDBIafT3W7jdnNVg1s6APOl13JGb7lzp5I6ONA
ewS7qh6dYjUrSsUFWwpDGDkchO7IGQWby1u1Xg0OBs+XVhRviTD5G085GBVibvwS
xXitW+7i/X79WTGP6T33/6lUQAmw9GIyzS5LYW4tUnUgQ2hlbiAo6Zmz5L6D5aaC
KSA8a29zdGVyQGRlYmlhbi5vcmcudHc+wsGZBDABCABDFiEEN0/yrQoSk1/QsMhP
GxMuAc7GrUYFAmVa7lclHSBUaGlzIGVtYWlsIGFkZHJlc3Mgbm8gbG9uZ2VyIHdv
cmtzLgAKCRAbEy4BzsatRiXSD/0Y2Iyoqpc7W+zA5jnlwwDrDUz1ccYQHSWOGrwu
2xk8iLZTJaXZq0T4aDT6BvLvYblRZdIffc3viJSHLIrmm3S1iHvbYiDwx10scmTZ
4ssAfkT26Ui53Moqap2Wkg6H26GxR409te4pn1Rvi9B5ZLK3KQdLZXt0R92pdZvD
jppJsnAMw86hTCLWXLxbcs1FyDCwf3eV5EgjqsiNOxb3p7dvD24bHJ0PgZBnq3uw
xDdYU/a2eag6kvFhJdyGyNJnIaoF8QQm7mdreD/ffXjjYGYxv4XIBMTF1NNoi9fz
z0PWua2K5xLpo5dsl39maaE/nX4Av+wFl3y4V+dm2racFsaVrPVNF38fOFUu6sZA
9WxHgRtLQOjP93TEXiT/DKRT2h4YMWZ5R08e2Tm009kyefyLVTVj1hf9UZ8HVM2w
6qEC80Zvg7/7vVsjSRqKnTTsc6MDxZW+srNT4c1h/Rdo6z90jnO0vihXDJCJlrN9
2hcFu9PJW5BdVszekVNUmOGTHzjla4mIUbZE2KPHw3lyaYZAXuEXa9cB6jIYUnqt
lWk/fSTEqrJ4PgTVQp2jrqviCnVkNLWPswVfmViTwRcw8oiANuYgt3bZ0w0tidoM
Xr2kBktRq/mRQXaE9Nq/idrhSf9VveulZlZdkkmnx/Z7st16BzXS9mcyYkoM2CxO
6tbtE8LBjgQTAQgAIQIbAwULCQgHAwUVCgkICwUWAgMBAAIeAQIXgAUCTGiYFwAh
CRAbEy4BzsatRhYhBDdP8q0KEpNf0LDITxsTLgHOxq1GNE8P/jbyr04jao8Mt8xH
i2IncYjH8LBwE9NQygzOOmIC+eYdjBDIgpAW7b7+aMQ44KbFSHECxxiiXStsl+nl
0KxtE+g4/N+betMcehdEEPTK6r83yliyH5BBRBOgoDm24q4KaCInIyG8zUDNoeod
q+mKIBMMiF20BoTGk50w2LWnUPkGB5iSBL3FMYea5WbDQd8SSwAE0J10/XuWOenP
9K5W6j6A0FWV7wN+cSPs5KMcaPT5ScL3Jnq+HwVj/imYfEt3vi7hnm9ndV7Y0yBC
raBnVuU92PtQwqRyhorEcHEyMxZtx1t+36H5tY5I9qxplg5vEITOvCbhgTuitBmX
SEZfpJOlgnaHwV2LA48a/s61yp9QoeBKOz6l5h0mYzhnzDNcWbEZnh9ZevAQccHy
DPtBjkORT4uVHuyFbQFOR1hOe5NS9+6/1qanfejCTZ9BUHL2utK3sjXFPEFJdIlk
5+8mbwRk3iQISuqNoLaIa7s+WyfJhWW7xg2d98MmF1VtRONkV+FR+scHghJ0PWn6
+baGzorwvpRUohGoIZaSaoAnnF4QAyjDzUEHPuGNJy0pRSra+yF9U4yqp6UKyKWY
W8Rk/IztXirk3Wq+xxpJFjSP7lvHtcQpJFlB33oqMkNE7AqSPW8VN7cIEz2K6S5H
absYkhIhfgoO4q3dlFcbmgf7pwUwwsGRBBMBCAAkAhsDBQsJCAcDBRUKCQgLBRYC
AwEAAh4BAheABQJK28wdAhkBACEJEBsTLgHOxq1GFiEEN0/yrQoSk1/QsMhPGxMu
Ac7GrUaQMw/9HvvXLT6KPTcSYiHBKUOGFAjJFiCxGyoKOA8azeqHhRZ0e7ej9dKA
7BaNnZwoQxcHtGQkz3IQgivSWfPCowti44u38gGQd3mFVjTyHmWMbiTdsfMcmJaB
MVYrmDqnz4EtkeqhOXEJLMzNNndJ/uowSqLfnlVpIJF+vX7OVHV/xe+eygezKdes
uMqw15F5WQv+tLNlVncr2fEB3lGH1t7wSwRQs0KoRx5vBAyYtr7jpSOv1yWY4YIP
fVW3Q/QdwfGLiog0U4PfSYSn3G8bP2TjH2oVZryZx5DLhhwRojUGIH2KutCNYKOj
RFTZW9/B/5wqKYO/OKkaPBr2l7tnxhyZhjtD8677CC2L7GZk5pthLvFT2LLhffWe
iB+qFiGzYYGZD5HMw22xdPdZ4rweYsTOTafioVLkcDl70c9Cn8zZ7cx5+ICaDwpH
qxFg6In5Z2SZWwiVSggUZKvvYQPet98mhsHhYE8vInzSHaJgdp/AU2sP1gbIjq3w
Q+wv8JZBFqsZWY6mVlbETpDGN4vyssxZamKfL9wUwWgGusHZIcbghDD59IVApfuB
j76q2TNdAlBoTo6pWUuulb8CcC/rZ3CWH71P3hVU22BXdIfehE4FqnfBhQXVCNIS
777T8iZeYX1z/OEXx+6BSvhiC2azCw4NYmjnAw6z6ypiBER80cXQHVzNK0thbi1S
dSBDaGVuICjpmbPkvoPlpoIpIDxrb3N0ZXJAZGViaWFuLm9yZz7CwZEEEwEIACQC
GwMFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AFAkxomHQCGQEAIQkQGxMuAc7GrUYW
IQQ3T/KtChKTX9CwyE8bEy4BzsatRkthEAC5cANjA3rTFBrTj4qhwP259WYyEWnX
/sVqCrmfpENsmjlY5rIdSN3fYzXbIAjdY54bXMjZHAHTfdM/FxmDGKTF7DnJMND3
8dg6MhW0SN5iun1ocGOwvOsMGkDwtbXNyEyIEJIzdQZuhtCaQMadBAd7nVwrv85M
nVfgwcbY+5ZY66+g6qFiNwqlqwa9vSotGVjUOCL2SODMw32fXq+ep/UiWpNN9YqZ
heVHTvnzrlJC5MrY0Y5kdptXBPHxZhhGl03EJRR12lz0cEKcpFPn08mJauoHUBLm
0+pK5nfLBSYO+W5yPlD1N0rKRaULTnuQletv2jLfYtNNSHlRhdbVUxVBw0lPXSV1
gRxXBdrPl8s+n7o0+Z8imwlBJwpUUKHoo6NurRQgIR5NMf6mTGxq+iw6txUnrYzB
ObDf4pmMjzE4xfj1eDsubJ9MjByXxRdISaoekwID5JEnI62vTBwgxi5fy+GItazX
8UVgINftg8eDoNH4SE1zCraw7Ji1KvOj46eq0ZU9TL/8l4u8HP6Q+RFVbGp2VKHZ
L4wz9Mh/DgFZHdXvDLlYZ/s8B0RA8L4Fj25swdlGIZfte+fmfSWaMvGDvaD/DSiM
8YXby9BJA9pWFEaSzA5izIJDHsG+mUEXggPcMJBjOTQ5zerH8D5njzsz0VwFtG0f
UPMgOEGycAJijcLBjgQTAQgAIQUCTGZUdQIbAwULCQgHAwUVCgkICwUWAgMBAAIe
AQIXgAAhCRAbEy4BzsatRhYhBDdP8q0KEpNf0LDITxsTLgHOxq1GxUoP/j+pZfQw
Z2p/6pubhV2bbhmR3PW98Dye4VHzlne08W85YwZl+pw+0fVa4F14Yz6Q2t7kEp7k
NnQpgpRQVQautOiFgWx1hC6kYaTg97bZwo6KcyY1XCJO/b6ftAmgrAgM8jiUo0fo
fVJQyzha6GOGuASfbAN8UjpBnfPj1PDCH4nGTWT1OEc+bw3vBkTLUMGk9Nohyd+v
/gNXwOeTP9djasWLBKLqj6ztAWDiWSrKPIR43WO52PJPsnjJZe0XH0ncZVnz4skD
G7scNMLs3lyNxg8bYInyXY9f78LY0mZ6O2H3k/3aKGddcevY7Bccqf1zyBbNCzEQ
/B3kgCzbi07ksP4+L4jOvttvbQvua5/efabgh0Z67QwTuMKXJQ328MQRPMnU4Upn
NMuYDEG7wQlQk+FBWWOKlfqQ/i25I+cZvwy9G1i3Leumyoh6V5ZeEV+wc5/pVaN5
UFIc+0I+WJAhLjMSHSRU6t36tGiWeBWbjBdLatuF/9FX1uMdvsGrwytZ+ULuAoic
GCBW5UkuP1llnVwXqbCaG4cw3GCCGkqZjC4Lyd+jcmC+PXtinRgj7PaN85GcxiKW
zXaWmho5vovjrGnpZ8MsRz/X8q5AKB6dkuNjWJacuPYrRK91+hgtNcSaEZ2jZC/k
S6SnZIJJY9y7eP9AKyd1NnGJvE+AVuQllGCmzTNLYW4tUnUgQ2hlbiAo6Zmz5L6D
5aaCLCBLYW4tSnUpIDxrY2hlbkBtb3ppbGxhLmNvbT7CwZoEMAEIAEQWIQQ3T/Kt
ChKTX9CwyE8bEy4BzsatRgUCXHE0dCYdIE5vdCB3b3JraW5nIGF0IE1vemlsbGEg
YXQgdGhlIG1vbWVudAAKCRAbEy4BzsatRngzEAC7ui7UNCJI2VC29B7RQnMmLZUS
wToGLxd2zB5wjfeeIyunuf+4sSZyvzDojVKWSVfebV5x1E1/loU/KwbxXZy4EqL/
0QY6FCgb0rkl0vAXSEmJS13LtFCIVJpKxp0TAXjigEN8WJlKK+u6GuGlAyRY3si6
0yBpBll/P6b3IYO54nL1BB5A0yXtcWH7SeDrPHxgCEKi0kf8t9KEOEfSsFedMAjN
sveeJ7yi7TVmoGkr/UvUog/D565HTyyThuN33enyLDLQhsAk+zTc7qRH2ZeAHQFK
ogoyX1bfgZrlfeZiRzKOLKGt8HinmzI4kDAEEcEUs2BT+v9yG5Zu5epNT5JkwVpK
N98lGkaVmKlRsB5GpEiifKxEpGoPyCSa1BRRrts9X/EUzeo83BWEntp0fFUlk2rW
KlsCPVUDJui/CZvVuz3ZPR3Mx0A9M0ZXpZHpiQc5gPU+Kigg0XwYBH06P8kxiSlM
2fQM0QsinKdwL1Q6y4piEe7OdA/wDHZX1vs9bWeEqWTvgch3GVbuq5TmyXK7LNIC
Cm2vM+J6/oBVrMem2diFZHLiLg+QQzYeRWw8ZVnr3T8BG8gXG9lCOqyKbMZ+0y0h
Gn9RsLsWlKWtGiHdIKZcbYFJgAuhzzM9RpSH98HMtTKvoNV7Oyt+s5WD5UylxVUh
z79VBMN7PK0SAPr6IsLBjgQTAQgAIQUCT4b4egIbAwULCQgHAwUVCgkICwUWAgMB
AAIeAQIXgAAhCRAbEy4BzsatRhYhBDdP8q0KEpNf0LDITxsTLgHOxq1GDEEP/2yP
XF/kr+HE/AsLGk67a3NqR0fto67De8NTB0tc9IVNFEsFwbK0+7vvLXd7K0Z3sfB+
vdOIS8PQKyo7FWVeaZ78m8lcCRoONXgBNGx+Q5b2OJTYql7c/MSpyV5U3ke2doXl
7cXXasXXUaxplYu5JTCYoUzDYc/HkOGU+HWtOJLWbP4QtlF82slRnTTEB/8Ho1v2
5xp/RlXlRUAhGpAWVfvFSQEhbratBXFXrTYzYSOagP6TuNDjEtZKwtSSO871okrj
6eleo5NWjUQxzc/9OmkJ3dXccFRkOQHukQmYjyyKr5WArM1e5mDUplP7PSnhcA9o
qMQxv4hX4SeU4Mo5RWmByHt1t9uNTAWk1eY7+KP8EYR3MMdSevS6jMAubuudg2lQ
MEFWnez1CGn8u5TANyNBBJspoUCcTcDVOcq3cVM3HPYmvd58xWNpMo17+aEHpe/g
gkbzx7NGPlJDPwW8evEfc8ns875O3/iY4wNIo4QEPBJ87r2LsKnbCzkRtubEVlX4
idv/viRxZXLDcREWZVHmGk5W0bxzsAeBAhjRV8sViJKOTa/dZ4oT5hbusu+z14vR
HYo/OuG03puXgkyZYlYYlEC9rDpivgLpBCBMHEquS9wUebmLFeB1IYDKP27Xm4iu
nLF292/UxR8pNtKjTVmYHjNDR9TY1V4iGf3UXeF1zsFNBE6Nc44BEACsvhECg1nZ
imEsNqv7QvP3jQyHC4c/i/ZXZUzr9UAkBlq5RWXDUZO/ErNJGIrJGOGWvdnvA+Ou
gMcXoZWia7byR42FlHsXJZ6s3Q6/LHQcxIKXvmcL+2yy61ysOK4QmjysxlbFHWDU
X1w4rveA3bAyvJPdPJSBgBIi7t9bsmih441IPf4wiXb8qaHI4DhYSMu95ByWDjKT
fBx7VwLmGP9n+FprTp8jYI1EOv2MufUyuPdSblxhCKzCLRxKsW5lOqR4hFrSBPAA
onvGv+w4bAQoM7Ehvh26rC49xsk0yivEP0AaPNCMvkMb4ZhQLB6IZVHG683z+LeU
WnfBxayl3U1odb5lOiwfIJpDlvKVDV3XZMocDXqZljzzw0ZUf0zj0EXA//Xa+7jj
AiB/UhM3VcLdPKj785XQmLRkeMn59O1kep90QYUf/UypDT41XXQbQ6w+OfFU8r24
faGczNyb9dVhcgeBA+hFWlKM3At/POi+OTjIG+TtVTjJB78OUo+OFnMmMzoF2awC
cGkUK1qW/l8J+ulf4FGAWN7WtfK9pCcCxD5P0pOtBFBNznbjD+w+diBpqvOK9LGK
RAfa29KH4dWKIf7YF0JjMzQDIhNwsMvi+KQ7jFrwT6wxb+7LKPmUtvMMAYw/Va+A
M7A1lYTDelOv+FVvSB/bU5TF5anANYSNHQARAQABwsPjBBgBCgB4BYJpiKD8BYkb
6/AICRAbEy4BzsatRkcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBn
cC5vcmfdUn+0jPT/aWvyf4K/ID40E1QZ7j1CFI5QvP14NTIzhAIbAhYhBDdP8q0K
EpNf0LDITxsTLgHOxq1GAh/BXSAEGQEIAAYFAk6Nc44ACgkQCjk1SrblfeELpg//
Zt/+ju7lO8uAJ0RHlk8EksY/KZ4H0uJJrw0ejFR4Dr9KvgKaP3sWSxtunz2+vMfp
dLLYDQY5VXq8mkYZuYogQhDiWx4pDQryez/pEi/Ybe+UsNFDJ5VOpPkVmQgYQXIa
SO/J8JRZaymtwa79wtoGa1P5cWEhXdPEUZQKZcEeEuTrCIp/4gFgmh/1hHghBn8W
81HxqsbiVAE7ShIsRrq08k+wD0ClFpVzETqJ9EtSX5w2Xq9OgBENYUP+v1bZMw9v
8Sq6w1fdW4ld21g5DTIQnvjG3GaF7sqiD3h2aWoeyFqCITFuW7wFvJ2rLeYfayW0
PT/ifv4Xdf3qkPIz60P5vLSPIpjcwlydZ7SiMEvcvmQYE5G6pZTybWi9dZSDa8lG
RKjDswjCBgNGesSkJWnjLbpvw51j+yvQetugB7YCBDLSCUTmp6zbu9D6WAlanq6K
9MyAelSeoAzn+XrvhXxqaKEZogAbo4R9HiTl+Eawp7iDFMGpxtf9lNknQ+3NHdMc
L7LV+KF0xum3J6J7pmVponRQW1EX1GSbeNv82+SmyDpmfahr2MCVbJ9JIQOq6hpm
3RRcnZgIWEaYwkpRscFtUkpwyXbkmLNA+vtmiY7oLGnI4qZlLlTfwimq02jukRD7
DKIDPD3pUvj4443toMBjMV5JSjz7EORu1BS9EMnxedWplA//VuoTb9hvB0i/QqU/
dAN+PWH8Po3EU3j8FB4FE80YrF4tLJlRN7CY64m2FR0fEHf+OfWlqy1y8fJNMBU8
eXXxxGK+4mI6Pp4Z4k9DnVrby3aOr/8XhWMcgf9u5T57UYlDbnvRLOhN28uZvaAi
WTntdaUnbdRe0HmV7kbtr/bH58AMp9eoT2chboRTChNqfSGCBAouCV8/5mDV43S0
ph4+5Tc+WLIPL6KY+c9Rvf8w9GZRJSA6OQI31l9bpyHm/Mvp2g8QtGlWZhzfY9hf
uiPfz8zEOKZknH2we7l4fku8hq+a5Wsx13BK+faTWGnykGb0YILf6slRnaP4v0oK
2//0lXH0xQaTMbUDoLaL0EkBq1uQOWuvzIcXr4enpUzkCSWgN92XabfoEekM2ue4
VIl1X4i/ZVohFcPxWbeu6+ouU8v+Rf4q2dcYpgRNISC2G2F09EhP87s4oMWj5Z+U
Ud4aa2xmpBOiZ+PD/PyjMxWdU5iBSSrtnaR/9aY2yZqXFQLeh33c6tNuiXUEok9U
jKwNM+AAEsCHMG5ev4LVBgPFa5yf+NDG34USFGHpLKmGARzLMsAgQQWnUIAd4UBY
535/ehitj3ZPRQFUBTJ60yFaaYW5VgdbMK8CjlkxqUX/i4ubEhKrc+CM7PEiCJ/6
RDF51/t9w7b+gERXTy3cHldz5+fCw5UEGAEIAAkFAk6Nc44CGwICQAkQGxMuAc7G
rUbBXSAEGQEIAAYFAk6Nc44ACgkQCjk1SrblfeELpg//Zt/+ju7lO8uAJ0RHlk8E
ksY/KZ4H0uJJrw0ejFR4Dr9KvgKaP3sWSxtunz2+vMfpdLLYDQY5VXq8mkYZuYog
QhDiWx4pDQryez/pEi/Ybe+UsNFDJ5VOpPkVmQgYQXIaSO/J8JRZaymtwa79wtoG
a1P5cWEhXdPEUZQKZcEeEuTrCIp/4gFgmh/1hHghBn8W81HxqsbiVAE7ShIsRrq0
8k+wD0ClFpVzETqJ9EtSX5w2Xq9OgBENYUP+v1bZMw9v8Sq6w1fdW4ld21g5DTIQ
nvjG3GaF7sqiD3h2aWoeyFqCITFuW7wFvJ2rLeYfayW0PT/ifv4Xdf3qkPIz60P5
vLSPIpjcwlydZ7SiMEvcvmQYE5G6pZTybWi9dZSDa8lGRKjDswjCBgNGesSkJWnj
Lbpvw51j+yvQetugB7YCBDLSCUTmp6zbu9D6WAlanq6K9MyAelSeoAzn+XrvhXxq
aKEZogAbo4R9HiTl+Eawp7iDFMGpxtf9lNknQ+3NHdMcL7LV+KF0xum3J6J7pmVp
onRQW1EX1GSbeNv82+SmyDpmfahr2MCVbJ9JIQOq6hpm3RRcnZgIWEaYwkpRscFt
UkpwyXbkmLNA+vtmiY7oLGnI4qZlLlTfwimq02jukRD7DKIDPD3pUvj4443toMBj
MV5JSjz7EORu1BS9EMnxedUWIQQ3T/KtChKTX9CwyE8bEy4BzsatRiW0D/49C7Fn
hhNbu2Kb6Nt5h9VjZ0mkKn8Com4uNbLcGLDJQPGObc6XKEyrEhb0W4NCyKbelAl6
NCa9MeItjv3Vj2I9Nqo6qYZU7eNC9vNZPUs5byTbveRjenN3k5c2NyQQZk0Vw6UJ
aFi++qLZEnFwl7EuKFULLCzUgUNtIhuSv6DLxS0hW0dNLQ2W+5FYouQauqc8SUVA
adr01ZlZtD8/b8RbOuUIfvWbXP5s4FeJaiZ65q136amvBjD2quOUr+UdQTc5cVoC
0OBQnC1sqq4f1kvTxBxUAnw+nWuyM91mg+MI19AXNhVMaopXQY3QbaYMKxcZKffa
0iN7njJ1VJ3qoHazVSTYPIAF2ZoY9gQ/Iszwr4WdD/zwDBOJ60tyW80iRJGVwy8u
Hyu3C+PDrpWcyVk2DTZrxM90ecNrWx78tBP9HQ3mZTVkZC31l7PvlJSFlbMJmALL
3Ke8HDSETDt+A/Lm6IkhBH4C1743q/HJmUdIi1srgHlkrSWYx2cgkqT7FoD3BKEf
lZU20d908DKdGohJqu2Z1wgJmjw73rXidjxzirtuEWIdZkbY2vs21SYxoraRsRcp
vnNnwORb37wIvABB0VoM6MjYTHmhRLoPWYCvapdk0XUoc5iGr3ulohTbeK2yQri3
g2bNW/yO73wb5ad99AfQP25StwVjIn+7IAxvrc4zBGm4/6AWCSsGAQQB2kcPAQEH
QDtogMyeZOngZDtPd7wfbU9q0Ub9u3A26kmG6nKXFpJ2wsKDBBgBCgE3BYJpuP+g
BYkFpI+9CRAbEy4BzsatRkcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lh
LXBncC5vcmeBfZF5fSW/F42syOx2xnr8hcLEv5byNTga12o6bjRnvAKbAr6gBBkW
CgBvBYJpuP+gCRDBFZyPeqU6uEcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1
b2lhLXBncC5vcmdT/3s5ZyPnEUkU3xX7dKBdaBgzo35QlmIYDTZnLLMDqBYhBDhc
hw/cUvsqt85l88EVnI96pTq4AADDMQD9Gz2/KlTqHKC88ChwDxKdiU4/Tst4o+Rk
jJrQFXKPD/EA/jQ3kI+gATRqsD4/UnTBoC1ql8lig3F+ZvvMp1EWp1QIFiEEN0/y
rQoSk1/QsMhPGxMuAc7GrUYAABw0EADAmam75hG++mRCGw61r2gj+aUKRwRW7WAR
f1c6gvyq9nB4X1+Mfe96KZ5r0sWe1PsCWfOBae0zA+BOWVA0XBXSEV96eYsG8YB4
F8JrKq37jQorFFs5jX/mejSqdSLUrzvrKA9kzteH8QQ55AvLdeL0INOFLmnnJ+R9
qNHezgtjtd+vd3Ku8jv7fb9rjv0WLSR0WnedYWtQwLIrClrf5ftnpQ1tEqaY9vAG
7MoApPvciKiT5MwITXH0GKP6ADnWBnZjdTIt3QEresEvPtkVPP/+4Hai+WQR5tXx
5dAtEqeJbmBUCRqQDNx80Tm+V0dDIK4fXTiywWm54+kD+GrMoWao6b9Si6bjJbQ2
BmMks9yiVYvtxZ9YmiesUB5ynp0ut7P831Ip0zmZK+YwADlwmxVm/A8bX2UlL+xg
poDuGLaVa/Tds3aj+cD7DO1VF/LyOXuFvYaG9sZZIC8cFdH3CitnY+86/swvrobt
p4zdwVw76ZLx654gMN+ndWodyKvoVYHIRLck/musHqykA/aQyR9p2Ywz0Uc0DEVn
NfFa9HcevTZc7bvHmASndk7bX2PB+FKbvze189UmesxlFsyyqjdwNc07n+M+IhOc
0PoKCKiD/Mmn1WRV4GDZo5W2098W7Bawahq27pdz61HbDbve9CEg7UWxyQOQI/Gf
co1c7plHq84zBGmIpLMWCSsGAQQB2kcPAQEHQLczgCmS29Iv+jOdV0aI8ID6+NG4
K2gMKzbLOHuI9uOkwsKDBBgBCgE3BYJpuQD7BYkAMa3ICRAbEy4BzsatRkcUAAAA
AAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmcQ9yfTgTTDX/aPYa8+
Lsk2Z6u5MlXcwESvdgtkO9szkwKbAr6gBBkWCgBvBYJpiKSzCRCY4qFEl7u+iUcU
AAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmfZjuNsneoe+HEJ
RcZrUEq0vi2kcOTDGrKUjWlq9XG5NxYhBKg7nAIXdubk1gJZRZjioUSXu76JAACO
3gEA6G55JqopbvLvHCMgwL4ei4xzAuiE3a6p/YNi6l394tgA+wQcfGfFc6Frt/my
+kFJa3SWhPqI1ZBeEuu/9Nep3iAKFiEEN0/yrQoSk1/QsMhPGxMuAc7GrUYAAM6p
EACwx9A1ML13l/4RnTCk2qK+O/YeV/rtzbdrtWScTlcLcgyQCsf5+qPAzpXuqEZ0
nBlH0FiPQNYoGO1r8hkUWHfjA1xw54dGjWndw+tUV8VWvNYaRsnAstXBjOroRLl9
NjnizGA8URHnoMUCiGeoVqfaH5sQV6VL8E7oAPZffs5qTUfMH95aFG++1kmouN6Q
Slx50Cu5vrccmJhGxc/fmUTFHab6pQbkjEOu6IkGLgzu08/rgfcJAghTEGuE/4BG
6epL8WTN0cz3L2asVvbgYX6TakiHCjEj2XPJLypwDtbUeMFDOsD3mYHW7NzO74IZ
+WWFexvHvVIucjy1ZY56z+0NCZPbF7MgQoIptA3zYYjTjesPCTHhxaNQrnIfMYUv
VbbNEjyqRZa4qE6NLjSo/qsJOjHs/pRffKWvVb1E98cwNkXLrU1sWbVE6fH69Hr8
V6HeGQk6EP9XaQ7lhWzzWZ8n8A2jAeRRcWrcJHFvP8BFLm974jn6EJAg7zrs4MXF
oqbyESSLdgo8e5piOAAA5uAlaf2OKc9vUKBopKIoK+ZKJH7AdnDArMFdJHCVSsSU
lHO5PFrBNkgX4JS0oySQQCM+Qg0XBQVX/NqzpJoiMzNNYiGlh0vLqu0N/o/8ciML
2eRkwd16MpZqNqogIgk98zvWYCrwGJcj1cVFF9J7FbO6wMLCgwQYAQoBNwWCaYik
swWJBaSPvQkQGxMuAc7GrUZHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9p
YS1wZ3Aub3JnWa8lEUhkml06AdIasOXXCW+WFaM2ut+/Ddupemk4IKgCmwK+oAQZ
FgoAbwWCaYikswkQmOKhRJe7volHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2Vx
dW9pYS1wZ3Aub3Jn2Y7jbJ3qHvhxCUXGa1BKtL4tpHDkwxqylI1pavVxuTcWIQSo
O5wCF3bm5NYCWUWY4qFEl7u+iQAAjt4BAOhueSaqKW7y7xwjIMC+HouMcwLohN2u
qf2DYupd/eLYAPsEHHxnxXOha7f5svpBSWt0loT6iNWQXhLrv/TXqd4gChYhBDdP
8q0KEpNf0LDITxsTLgHOxq1GAABeOg//f0pHfaXK76XaJiPSp/DObj015kC5F7Yu
/SJs02BUDURy9JSB4x9AP884B7o0Gd+M17NtuKkTYl1lbiRtVA1yWCvK+JsB8r/l
pIz9VzkxGiWUZ/vsEypecaNsylFFX1om0ht5CtBHsXpYVjnGwg2N/PN9re9ZDW9U
ajFnksPY2Q5sIvFr56UXaFvORZyZ87iM0XbNHSLgxOESp3jEtSDIqjnUeS8ZtOnU
/FExDFNQCZfUKgqHnKXi1wdIHn8Em1f9+V3PlEZ/OL8GFCizrqd0D955tx5xfVTk
xerDVP+YoIO24m+AYHHp8CoX4ZczWDAd18UFQPud+erA0gOBSrVQNpAUTybLyPxm
5Gvk7MNDBxIMe6ZKum76u38aWp1lzd3bGu+y5voxiIBHLircbRtjbFnIsaEJSdvO
oMnTomP3b8clkjYoFon/lUDeBisTyclmHj8xJ4IHX3tpnMg520SiXbjbry0R9w6Q
ZaOiEuV/mS4a/rU/LEwD75xnmAxldRImOyOmT4zF+9ib8GgutqwMFv4f9/m1/MKq
hTdPU3jy82HO4BLzEFfbJcgBNYJIJ0+ffFJfCtxVn/mVjWbST6vHwUwSgNBIBICM
ou31FfHD7ezOlUqz2IcIVOO5DiIZZqsQyS3rf3sLDsPxp43JP+zaz7DHAOv2ctpl
har1tyQ+rlM=
=Q4UK
-----END PGP PUBLIC KEY BLOCK-----
"""
