.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH chewing-cli 1  "chewing-cli 0.9.1" 
.SH NAME
chewing\-cli \- Tools of the Chewing (酷音) intelligent Zhuyin input method.
.SH SYNOPSIS
\fBchewing\-cli\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Tools of the Chewing (酷音) intelligent Zhuyin input method.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
chewing\-cli\-init\-database(1)
Create a new dictionary file
.TP
chewing\-cli\-info(1)
Display information about the dictionary
.TP
chewing\-cli\-dump(1)
Dump the dictionary entries into tsi.src formatted stream
.SH VERSION
v0.9.1