.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH chewing-cli-info 1  "info " 
.SH NAME
chewing\-cli\-info \- Display information about the dictionary
.SH SYNOPSIS
\fBchewing\-cli info\fR [\fB\-j\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Display information about the dictionary
.SH OPTIONS
.TP
\fB\-j\fR, \fB\-\-json\fR
Output in JSON format
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Location of the dictionary file
