.TH CHEWING-CLI-INFO "1" "April 2024" "chewing-cli info 0.8.0" "User Commands"
.SH NAME
chewing-cli info \- manual page for chewing-cli info 0.8.0
.SH SYNOPSIS
.B chewing-cli info
\fI\,<path> \/\fR[\fI\,-j\/\fR]
.SH DESCRIPTION
Display information about the dictionary
.SS "Arguments:"
.TP
<path>
Location of the dictionary file
.SH OPTIONS
.TP
\fB\-j\fR, \fB\-\-json\fR
Output in JSON format