.TH CHEWING-CLI "1" "April 2024" "chewing-cli 0.8.0-alpha.1" "User Commands"
.SH NAME
chewing-cli \- manual page for chewing-cli 0.8.0-alpha.1
.SH SYNOPSIS
.B chewing-cli
[\fI\,-h\/\fR] [\fI\,--version\/\fR] \fI\,<COMMAND>\/\fR
.SH DESCRIPTION
Chewing command\-line tools
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints help
.TP
\fB\-\-version\fR
Output version information and exit
.SH COMMANDS
.TP
init\-database
Create a new dictionary file suitable for system dictionary
.TP
info
Display information about the dictionary
.TP
dump
Dump the dictionary entries into tsi.src formatted stream
.TP
help
Print this message or the help of the given subcommand(s)
