.TH CHEWING-CLI-DUMP "1" "April 2024" "chewing-cli dump 0.8.0" "User Commands"
.SH NAME
chewing-cli dump \- manual page for chewing-cli dump 0.8.0
.SH SYNOPSIS
.B chewing-cli dump
\fI\,<path> \/\fR[\fI\,--csv\/\fR]
.SH DESCRIPTION
Dump the dictionary entries into tsi.src formatted stream
.SS "Arguments:"
.TP
<path>
Location of the dictionary file
.SH OPTIONS
.TP
\fB\-\-csv\fR
Output CSV format
