.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH chewing-cli-dump 1  "dump " 
.SH NAME
chewing\-cli\-dump \- Dump the dictionary entries into tsi.src formatted stream
.SH SYNOPSIS
\fBchewing\-cli dump\fR [\fB\-\-csv\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Dump the dictionary entries into tsi.src formatted stream
.SH OPTIONS
.TP
\fB\-\-csv\fR
Output CSV format
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Location of the dictionary file
